# Generated by Django 4.2.5 on 2023-11-26 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='cantPersona',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=15)]),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='correoElectronico',
            field=models.CharField(max_length=100, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='nombrePersona',
            field=models.CharField(max_length=80, validators=[django.core.validators.MaxLengthValidator(limit_value=80)]),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='observacion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
